// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateLink(ctx context.Context, url string) (*Link, error)
	DeleteLinkById(ctx context.Context, id uuid.UUID) (*Link, error)
	FindLinkById(ctx context.Context, id uuid.UUID) (*Link, error)
	FindLinkByUrl(ctx context.Context, url string) (*Link, error)
	ListLinks(ctx context.Context) ([]*Link, error)
	UnDeleteLinkById(ctx context.Context, id uuid.UUID) (*Link, error)
}

var _ Querier = (*Queries)(nil)
